namespace Nager.AmazonProductAdvertising.Model
{
    /// <summary>
    /// Search Indexes, more information located
    /// https://webservices.amazon.com/paapi5/documentation/use-cases/organization-of-items-on-amazon/search-index.html
    /// </summary>
    public enum SearchIndex
    {
        All,
        AmazonVideo,
        Apparel,
        Appliances,
        ArtsAndCrafts,
        Automotive,
        Baby,
        Beauty,
        Books,
        Classical,
        Collectibles,
        Computers,
        DigitalMusic,
        DigitalEducationalResources,
        Electronics,
        EverythingElse,
        Fashion,
        FashionBaby,
        FashionBoys,
        FashionGirls,
        FashionMen,
        FashionWomen,
        GardenAndOutdoor,
        GiftCards,
        GroceryAndGourmetFood,
        Handmade,
        HealthPersonalCare,
        HomeAndKitchen,
        Industrial,
        Jewelry,
        KindleStore,
        LocalServices,
        Luggage,
        LuxuryBeauty,
        Magazines,
        MobileAndAccessories,
        MobileApps,
        MoviesAndTV,
        Music,
        MusicalInstruments,
        OfficeProducts,
        PetSupplies,
        Photo,
        Shoes,
        Software,
        SportsAndOutdoors,
        ToolsAndHomeImprovement,
        ToysAndGames,
        VHS,
        VideoGames,
        Watches,
    }
}
